Conforming to syle guide (#37)
* Made edits on client side

exception: card image files are named cardNS.png (where N=0 to 13 and S=1st letter of suit).

* More conformance

* made card and cardTest style compliant, fixed windows specific paths, minor tweaks to UICardWrapper

* Yet more conformance

Also removed some obsolete comments.

* Made ServerState stle compliant

* Made GameServer style compliant

* Made player channel style compliant

* made RunServer style compliant

* Made RunClient use actual methods for safety and sanity

* Make ClientState style compliant

* Made testClientState style compliant and fixed bug from earlier rushed changes to make tests pass again

* added staticMethod annotations so it stopped complaining about them in eclipse

* Followed some pyCharm advice

PyCharm pointed out some places where I could clean up code.  Changed textRect to text_rect... inserted some spaces, etc.  More to be done.

* Make controller style compliant and swap interactive to turn_phase (although functionality has not been swapped yet)

* API updates for style compliance and comments on hand_status compilation

* Client stuff compliant

I believe that HandView, TableView, UICardWrapper and UIConstants are now style compliant.

* Added IDE related files to gitignore

* Actually removing ignore files since they weren't autoremoved by adjusting the ignore file